### ISSUE TITLE
Date & time picker

### ISSUE THREAD

**Issue by andy200486** [Baseflow/XF-Material-Library#139]
Will you implements date & time picker in the futur ?

Thanks!

**Comment by OdetteP** [comment]
Date and time picker is added.

**Comment by yankarinRG** [comment]
With xmlns:material="clr-namespace:XF.Material.Forms.UI;assembly=XF.Material" I get this error: "The type 'material:MaterialDatePicker' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built".
How did you build the sample app if MaterialDatePicker is in another namespace, which is "clr-namespace:XF.Material.Forms.UI.Internals;assembly=XF.Material"?
Even then you'd get this error: "Type 'MaterialDatePicker' is not usable as an object element because it is not public or does not define a public parameterless constructor or a type converter"

How to solve?
