### ISSUE TITLE
[Feature] Add UWP Support

### ISSUE THREAD

**Issue by christianlouislivioco** [Baseflow/XF-Material-Library#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sidiabale** [comment]
Hi, I was about to ask a related question when I came across this one. My question is not adding UWP support per se but more can I use this library in a project where I'm target UWP as well? If so, how would the widgets look? I ask because it's a Xamarin.Forms library so technically UWP should be in scope to an extent...

**Comment by contrix09** [comment]
Hi, currently there are no renderers for the UWP platform. It will renderer instead the native controls. I am planning to add support for UWP with the help of @christianlouislivioco .

**Comment by sidiabale** [comment]
Nice to hear. Great job guys!

Op ma 21 jan. 2019 05:31 schreef Dustin Catap <notifications@github.com:

**Comment by Druffl3** [comment]
@contrix09 How soon can we expect UWP support?

**Comment by mzhukovs** [comment]
UWP support would be _amazing_. This is such a great library, thanks to all the contributors!

**Comment by mzhukovs** [comment]
@christianlouislivioco contrix09  just curious is this underway?
